# ~/.config/stars the prompt to the right
right_format = """$time"""

[time]
disabled = false
format = 'ðŸ•™ [$time]($style) '
time_format = '%T'
utc_time_offset = '+1'

[directory]
truncation_length = 8
truncation_symbol = 'â€¦/'

[sudo]
disabled = false

[kubernetes]
disabled = false

[shell]
fish_indicator = 'ïœ¹'
powershell_indicator = 'ï‘ _'
zsh_indicator = 'ðŸ’¤'
unknown_indicator = 'mystery shell'
style = 'cyan bold'
disabled = false

[status]
symbol = 'ðŸ”´ '
# success_symbol = 'ðŸŸ¢ '
format = '[$symbol$common_meaning$signal_name$maybe_int]($style) '
map_symbol = true
disabled = false
